name: 'Hello Folks'
description: 'Say HI!'
inputs:
  who-to-say-Hi:  # id of the input
    description: 'Who to say Hi'
    required: true
    default: ‘Folks’
outputs:
  value:
    description: "Greeting"
    value: "Some value"
runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.who-to-say-Hi }}."
      shell: bash