name: test-n-dump
run-name: ${{ github.actor }} is learning GitHub Actions in ${{ github.event.repository.name }}
on: [push, workflow_dispatch]
jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.prop }}
    steps:
      - uses: actions/checkout@v3
      - name: Read json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          echo "::set-output name=update_catalog::$(echo $json.update_catalog)"
          echo "::set-output name=integration_type::$(echo $json.integration_type)"
          echo "update_catalog = $integration_type"
          echo "integration_type = $integration_type"

