name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  show-job-output:
    needs:  call-assign-from-json-workflow
    name: Show property value
    runs-on: ubuntu-latest
    steps:
      - name: Show Patch Version
        run: |
          # Get the patch_version output from the previous job
          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"
          echo "Output: $patch_version"