name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      patch_version: ${{ steps.read-json.outputs.patch_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Store json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          $myvar = $json.patch_version
          echo "patch_version=$myvar" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Check for var
        id: read-patch_version
        uses: actions/github-script@v6
        with:
          script: |
            const patchVersion = process.env.patch_version
            console.log(patchVersion);
