name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

#@patch-version-debug
#          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"

jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.update_catalog }}
      integration_type:  ${{ steps.read-json.outputs.integration_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Store json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          $myvar = $json.patch_version
          echo "patch_version=$myvar" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
