name: Update repository description
on: push
        
jobs:
  get-repo-description:
    name: Check the description for this Repository
    runs-on: ubuntu-latest
    steps:
      - name: Get description from manifest
        id: get_description
        uses: actions/github-script@v6
        with:
          script: |
            // check existing description from manifest
            var IS_EMPTY=
            core.exportVariable('IS_EMPTY', `T`);
            
  update-repo-description:
    name: Update the description for this Repository
    # if: ${{ env.IS_EMPTY }} != 'T'
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`New description: ${ env.IS_EMPTY }`)
