name: Update repository description
on: push

jobs:
  get-repo-description:
    name: Check the description for this Repository
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            const description-text = 'My MOST Text Description'
            const repo = context.repo.repo
            const org = context.repo.owner
            const owner = org
            const response = await github.rest.repos.update({
              owner,
              repo,
              description: description-text
            })
