name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

#@patch-version-debug
#          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  read-manifest-property:
    runs-on: ubuntu-latest
    needs: call-assign-from-json-workflow
    steps:
      #- name: Dump context
      #  id: dump-context
      #  uses: crazy-max/ghaction-dump-context@v2

      - name: Read manifest value
        id: read-manifest-value
        # if: needs.call-assign-from-json-workflow.outputs.patch_version == '1.3'
        run: |
          patchVersion="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"
          echo "Default Value: $defaultValue"
      #- name: Dump context
      #  id: dump_context
      #  uses: crazy-max/ghaction-dump-context@v2
 