name: github-output
# run-name: ${{ github.actor }} is learning GitHub Actions in ${{ github.event.repository.name }}
on: [workflow_dispatch,push]
jobs:
  read-default-output:
    runs-on: windows-latest
    steps:
      - name: Map type to topic
        id: map_type
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`map_type`);
            switch ('ca-gateway') {
            case 'orchestrator':
              topic = 'keyfactor-universal-orchestrator'
              break;
            case 'windows-orchestrator':
              topic = 'keyfactor-orchestrator'
              break;
            case 'ca-gateway':
              topic = 'keyfactor-cagateway'
              break;
            case 'pam':
              topic = 'keyfactor-pam'
              break;
            case 'api-client':
              topic = 'keyfactor-api-client'
              break;
            default:
              topic = 'empty'
              console.log(`Unknwon type: ` + repoJSONProps.integration_type);
            }
            core.setOutput('topic-label', topic);
            console.log(`Topic: ${topic}`);
