name: Update repository description
on: push

jobs:
  read-and-display-var:
    name: Set a property
    runs-on: ubuntu-latest
    steps:
      - name: Set foo
        id: set_foo
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Setting the output step foo = bar`)
            core.exportVariable('foo','bar')
      - name: Update repository description
        id: show_foo
        uses: actions/github-script@v6
        with:
          script: |
            const newVar = core.getInput('foo');
            console.log('newVar is ' + newVar);
