name: Update repository description
on: push

jobs:
  set-step-output:
    name: Set a property
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.update_description.outputs.foo }}
    steps:
      - name: Set foo
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Setting the output step foo = bar`)
            core.exportVariable('foo','bar')
      - name: Set foo
        id: second_step
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`foo = ${{update_description.}}`)
  show-step-output:
    name: Show property value
    runs-on: ubuntu-latest
    needs: set-step-output
    #if: needs.set-step-output.outputs.foo == 'bar'
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`needs.set-step-output.outputs.foo : ${{needs.set-step-output.outputs.foo}}`)
            console.log('needs.set-step-output.outputs.foo' + ${{needs.set-step-output.outputs.foo}})