name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

#@patch-version-debug
#          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  read-manifest-property:
    runs-on: ubuntu-latest
    needs: call-assign-from-json-workflow
    steps:
      #- name: Dump context
      #  id: dump-context
      #  uses: crazy-max/ghaction-dump-context@v2

      - name: Read manifest value
        id: read-manifest-value
        # if: needs.call-assign-from-json-workflow.outputs.patch_version == '1.3'
        uses: actions/github-script@v6
        with: 
          script: |
            console.log("========")
            console.log(`needs.call-assign-from-json-workflow.outputs.name = ${needs.call-assign-from-json-workflow.outputs.name}`)
            console.log(`needs.call-assign-from-json-workflow.outputs.description = ${needs.call-assign-from-json-workflow.outputs.description}`)
            const patchVersion = `${needs.call-assign-from-json-workflow.outputs.patch_version}`
            console.log(`needs.call-assign-from-json-workflow.outputs.patchVersion = ${needs.call-assign-from-json-workflow.outputs.patchVersion}`)
            console.log("========")

      #- name: Dump context
      #  id: dump_context
      #  uses: crazy-max/ghaction-dump-context@v2
 