name: Update repository description
on: push

jobs:
  set-step-output:
    name: Set a property
    runs-on: ubuntu-latest
    outputs:
      foo: 'bar'
    steps:
      - name: Set foo
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Setting the output step foo = bar`)
            core.exportVariable('foo','bar')
  show-step-output:
    name: Show property value
    runs-on: ubuntu-latest
    needs: set-step-output
    if: needs.set-step-output.outputs.foo == 'baz'
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log('${{needs.set-step-output.outputs.foo}}')