name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

#@patch-version-debug
#          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"

jobs:
  call-create-github-release-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  read-manifest-property:
    runs-on: ubuntu-latest
    needs: call-create-github-release-workflow
    outputs:
      release_version: ${{ steps.create_release.outputs.current_tag }}
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Read manifest value
        id: read-manifest-value
        if: needs.call-assign-from-json-workflow.outputs.patch_version != ''
        uses: actions/github-script@v6
        with: 
          script: |
            console.log("========")
            const patchVersion = needs.call-assign-from-json-workflow.outputs.patch_version
            console.log(`patchVersion = ${patchVersion}`)
            console.log("========")

      #- name: Dump context
      #  id: dump_context
      #  uses: crazy-max/ghaction-dump-context@v2
 