name: Update repository description
on: push
        
jobs:
  get-repo-description:
    name: Check the description for this Repository
    runs-on: ubuntu-latest
    outputs:
      is-empty: ${{ steps.get_description.outputs.is_empty }}
    steps:
      - name: Get description from manifest
        id: get_description
        uses: actions/github-script@v6
        with:
          script: |
            // check existing description from manifest
            core.setOutput('is_empty', 'T');
            
  update-repo-description:
    name: Update the description for this Repository
    needs: get-repo-description
    # if: ${{ env.IS_EMPTY }} != 'T'
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`New description: ${{ needs.get-repo-description.outputs.is-empty}}`)
