name: Update repository description
on: [push, pull_request]

jobs:
  show-job-output:
    name: Show property value
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            const fullRef = process.env.GITHUB_REF_NAME;
            console.log(`Output: ${fullRef}`);
