name: Update repository description
on: [push, pull_request]

jobs:
  set-job-output:
    name: Set a property
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        id: dump_context
        uses: crazy-max/ghaction-dump-context@v2
  show-job-output:
    name: Show property value
    runs-on: ubuntu-latest
    needs: set-job-output
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            const fullRef = process.env.GITHUB_REF_NAME;
            console.log(`Output: ${fullRef}`);
