name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

#@patch-version-debug
#          patch_version="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"

jobs:
  call-create-github-release-workflow:
    uses: keyfactor/cpr-release-checks/.github/workflows/check-files.yml@main

  create-github-release:
    runs-on: ubuntu-latest
    needs: call-create-github-release-workflow
    outputs:
      release_version: ${{ steps.create_release.outputs.current_tag }}
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Read manifest value
        id: read-manifest-value
        uses: actions/github-script@v6
        with: 
          script: |
            console.log("Hello")

      #- name: Dump context
      #  id: dump_context
      #  uses: crazy-max/ghaction-dump-context@v2
 