name: github-output
# run-name: ${{ github.actor }} is learning GitHub Actions in ${{ github.event.repository.name }}
on: [workflow_dispatch]
env:
  TEAM_PERMISSIONS: '[["one","foo"],["two","bar"]]'
jobs:
  read-default-output:
    runs-on: windows-latest
    steps:
      - name: Env Variables
        id: read-env
        env:
          FOO: BAR
        run: |
          Write-Output "update_catalog = ${{ env.FOO }} (exp. BAR)"
          Write-Output " TEAM_PERMISSIONS = ${{ env.TEAM_PERMISSIONS }}"


