name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  show-job-output:
    needs:  call-assign-from-json-workflow
    name: Show property value
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description
        id: update_description
        uses: actions/github-script@v6
        with:
          script: |
            const patch_version = `${{ steps.read-patch_version.outputs.output-value }}`
            console.log(`Output: ${patch_version}`);
