name: New Starter Workflow Ubuntu Mixed
on: [workflow_dispatch, push]

env:
  NAME: "name-value"

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@patch-version-debug

  read-manifest-property:
    runs-on: ubuntu-latest
    needs: call-assign-from-json-workflow
    steps:
      - name: Read manifest value
        id: read-manifest-value
        run: |
          echo "NAME Value: $NAME"
          patchVersion="${{ needs.call-assign-from-json-workflow.outputs.patch_version }}"
          echo "patchVersion Value: $patchVersion"
          echo "patch_version=$patchVersion" >> $GITHUB_ENV

      - name: Read it again
        id: read-it-again
        uses: actions/github-script@v6
        with:
          script: |
            const patchVersion = process.env.patch_version;
            console.log(`patchVersion Value: ${patchVersion}`);
            if (patchVersion !== '') { 
              console.log(`patchVersion Value is still: ${patchVersion}`);
            }
